# Generated by Django 4.2.6 on 2023-12-24 15:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diagnostic.carbrands')),
            ],
        ),
        migrations.CreateModel(
            name='CarYears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2023)])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diagnostic.carmodels')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/diagnostics/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diagnostic.carbrands')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diagnostic.carmodels')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diagnostic.caryears')),
            ],
        ),
    ]
