# Generated by Django 4.2.6 on 2023-12-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarBrands',
            new_name='CarBrand',
        ),
        migrations.RenameModel(
            old_name='CarModels',
            new_name='CarModel',
        ),
        migrations.RenameModel(
            old_name='CarYears',
            new_name='CarYear',
        ),
    ]
