# Generated by Django 4.2.6 on 2023-12-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0003_enginetype_diagnostic_engine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
