# Generated by Django 4.2.6 on 2023-12-28 08:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0005_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('file', models.FileField(upload_to='media/diagnostics/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diagnostic.carbrand')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diagnostic.carmodel')),
            ],
        ),
    ]
