# Generated by Django 4.2.6 on 2023-12-31 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0008_diagnostic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caryear',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
