# Generated by Django 4.2.6 on 2024-01-06 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autofind', '0005_alter_slot_voice_call_number'),
        ('shop', '0014_shop_phone'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='cart_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cartitem'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autofind.slot'),
        ),
    ]
