# Generated by Django 4.2.6 on 2023-12-20 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autofind', '0003_slot_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='brand',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='car_model',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='car_problems',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='voice_call_number',
            field=models.IntegerField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123456789'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
