# Generated by Django 4.2.6 on 2023-12-20 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autofind', '0004_slot_address_slot_brand_slot_car_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='voice_call_number',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123456789'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
