# Generated by Django 4.2.6 on 2023-12-16 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='media/shop_photo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif'])])),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_images',
            field=models.ManyToManyField(to='shop.shopimages'),
        ),
    ]
