# Generated by Django 4.2.6 on 2023-12-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_about_description_productimages_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='about',
            field=models.ManyToManyField(to='shop.about'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.ManyToManyField(to='shop.description'),
        ),
    ]
