# Generated by Django 4.2.6 on 2023-12-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_products_about_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_images',
            field=models.ManyToManyField(blank=True, null=True, to='shop.productimages'),
        ),
    ]
