# Generated by Django 4.2.6 on 2023-12-31 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_customuser_phone_and_more'),
        ('shop', '0012_products_quanitity_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='expert_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.expertcategory'),
        ),
    ]
