# Generated by Django 4.2.6 on 2024-01-01 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_shop_expert_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.CharField(default='1234567890', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123456789'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
