# Generated by Django 4.2.6 on 2023-10-20 08:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_hotel_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.expertcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='whatsapp_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123456789'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
