# Generated by Django 4.2.6 on 2023-10-20 14:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_expertcategory_expertsubcategory_delete_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='uploads/aadhar_card/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='driving_card',
            field=models.FileField(blank=True, null=True, upload_to='uploads/driving_card/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='expert_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.expertcategory'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='uploads/pan_card/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
