# Generated by Django 4.2.6 on 2023-10-21 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_aadhar_card_customuser_driving_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expert_subcategory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.expertsubcategory'),
        ),
    ]
