# Generated by Django 4.2.6 on 2023-11-13 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_expert_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expert_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.expertcategory'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='expert_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.expertsubcategory'),
        ),
    ]
