# Generated by Django 4.2.6 on 2023-11-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_expert_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='Jabalpur', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(default='Madhya Pradesh', max_length=150),
        ),
    ]
