# Generated by Django 4.2.6 on 2023-11-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser_city_customuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
