# Generated by Django 4.2.6 on 2023-12-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_shopsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSubscriptionCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quarterly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('half_yaer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yearly', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
