# Generated by Django 4.2.6 on 2023-12-27 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_shopsubscriptioncharges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopsubscriptioncharges',
            old_name='half_yaer',
            new_name='half_yearly',
        ),
    ]
