# Generated by Django 4.2.6 on 2023-12-28 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_diagnosticsubscriptioncharges_diagnosticsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '123456789'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='whatsapp_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '123456789'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
